#Adapted from https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/exercise-solutions/card-game/part-11/api-gateway/src/main/resources/application.yml
spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: discovery
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Auth
          uri: http://auth:8080
          predicates:
            - Path=/api/auth/**

        - id: Trip
          uri: lb://trips-service
          predicates:
            - Path=/api/trips/**
#        - id: User-Collections
#          uri: lb://user-collections-service
#          predicates:
#            - Path=/api/user-collections/**
#        - id: frontend
#          uri: http://frontend:8080
#          predicates:
#            - Path=/**