# From https://github.com/arcuri82/testing_security_development_enterprise_systems/blob/master/advanced/exercise-solutions/card-game/part-10/auth/src/main/resources/application.yml
spring:
  application:
    name: auth-service
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: rabbitmq
  datasource:
    url: "jdbc:postgresql://postgres-auth:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: validate